version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile-front
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile-end
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/ecomdb
      - UPSTASH_REDIS_URL=redis://redis:6379
      - ACCESS_TOKEN_SECRET=supersecretaccesstoken
      - REFRESH_TOKEN_SECRET=supersecretrefreshtoken
      - CLOUDINARY_CLOUD_NAME=yourcloud
      - CLOUDINARY_API_KEY=yourapi
      - CLOUDINARY_API_SECRET=yourpasword
      - STRIPE_SECRET_KEY=yourkey
      - CLIENT_URL=http://localhost:5173
      - NODE_ENV=development
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
